version: '2'
services:
    javacollections-app:
        image: javacollections
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://javacollections-postgresql:5432/javaCollections
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    javacollections-postgresql:
        extends:
            file: postgresql.yml
            service: javacollections-postgresql
