version: '2'
services:
    javacollections-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/javaCollections/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=javaCollections
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
